from django.db import models

class Dinner_Post(models.Model):
  title = models.CharField(max_length=100)
  image = models.ImageField(default='default.JPG', upload_to='image_posts')
  ingredient_1 = models.CharField(max_length=100, default='1')
  ingredient_2 = models.CharField(max_length=100,default='1')
  ingredient_3 = models.CharField(max_length=100, default='1')
  ingredient_4 = models.CharField(max_length=100, default='1')
  ingredient_5 = models.CharField(max_length=100, default='1')
  ingredient_6 = models.CharField(max_length=100, default='1')
  ingredient_7 = models.CharField(max_length=100, default='1')
  ingredient_8 = models.CharField(max_length=100,default='1')
  ingredient_9 = models.CharField(max_length=100, default='1')
  ingredient_10 = models.CharField(max_length=100, default='1')
  step_1 = models.CharField(max_length=100,default='1')
  step_2 = models.CharField(max_length=100,default='1')
  step_3 = models.CharField(max_length=100,default='1')
  step_4 = models.CharField(max_length=100,default='1')
  step_5 = models.CharField(max_length=100,default='1')
  step_6 = models.CharField(max_length=100,default='1')
  step_7 = models.CharField(max_length=100,default='1')
  step_8 = models.CharField(max_length=100,default='1')
  step_9 = models.CharField(max_length=100,default='1')
  step_10 = models.CharField(max_length=100,default='1')
  time = models.IntegerField(default='')
  drink = models.CharField(max_length=100,default='')
  stars = models.IntegerField(default='')

  def __str__(self):
    return self.title

class Snack_Post(models.Model):
  title = models.CharField(max_length=100)
  image = models.ImageField(default='default.JPG', upload_to='image_posts')
  ingredient_1 = models.CharField(max_length=100, default='')
  ingredient_2 = models.CharField(max_length=100,default='')
  ingredient_3 = models.CharField(max_length=100, default='')
  ingredient_4 = models.CharField(max_length=100, default='')
  ingredient_5 = models.CharField(max_length=100, default='')
  ingredient_6 = models.CharField(max_length=100, default='')
  ingredient_7 = models.CharField(max_length=100, default='')
  ingredient_8 = models.CharField(max_length=100,default='')
  ingredient_9 = models.CharField(max_length=100, default='')
  ingredient_10 = models.CharField(max_length=100, default='')
  step_1 = models.CharField(max_length=100,default='')
  step_2 = models.CharField(max_length=100,default='')
  step_3 = models.CharField(max_length=100,default='')
  step_4 = models.CharField(max_length=100,default='')
  step_5 = models.CharField(max_length=100,default='')
  step_6 = models.CharField(max_length=100,default='')
  step_7 = models.CharField(max_length=100,default='')
  step_8 = models.CharField(max_length=100,default='')
  step_9 = models.CharField(max_length=100,default='')
  step_10 = models.CharField(max_length=100,default='')
  time = models.IntegerField(default='')
  drink = models.CharField(max_length=100,default='')
  stars = models.IntegerField(default='')

  def __str__(self):
    return self.title

class Dessert_Post(models.Model):
  title = models.CharField(max_length=100)
  image = models.ImageField(default='default.JPG', upload_to='image_posts')
  ingredient_1 = models.CharField(max_length=100, default='1')
  ingredient_2 = models.CharField(max_length=100,default='1')
  ingredient_3 = models.CharField(max_length=100, default='')
  ingredient_4 = models.CharField(max_length=100, default='')
  ingredient_5 = models.CharField(max_length=100, default='')
  ingredient_6 = models.CharField(max_length=100, default='')
  ingredient_7 = models.CharField(max_length=100, default='')
  ingredient_8 = models.CharField(max_length=100,default='')
  ingredient_9 = models.CharField(max_length=100, default='')
  ingredient_10 = models.CharField(max_length=100, default='')
  step_1 = models.CharField(max_length=100,default='')
  step_2 = models.CharField(max_length=100,default='')
  step_3 = models.CharField(max_length=100,default='')
  step_4 = models.CharField(max_length=100,default='')
  step_5 = models.CharField(max_length=100,default='')
  step_6 = models.CharField(max_length=100,default='')
  step_7 = models.CharField(max_length=100,default='')
  step_8 = models.CharField(max_length=100,default='')
  step_9 = models.CharField(max_length=100,default='')
  step_10 = models.CharField(max_length=100,default='')
  time = models.IntegerField(default='')
  drink = models.CharField(max_length=100,default='')
  stars = models.IntegerField(default='')

  def __str__(self):
    return self.title
