# Generated by Django 3.1.4 on 2020-12-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.JPG', upload_to='image_posts')),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
            ],
        ),
    ]
