# Generated by Django 3.1.4 on 2020-12-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_auto_20201229_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert_post',
            name='drink',
            field=models.CharField(default='water', max_length=100),
        ),
        migrations.AddField(
            model_name='dessert_post',
            name='time',
            field=models.IntegerField(default='30'),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='drink',
            field=models.CharField(default='water', max_length=100),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='time',
            field=models.IntegerField(default='30'),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='drink',
            field=models.CharField(default='water', max_length=100),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='time',
            field=models.IntegerField(default='30'),
        ),
    ]
