# Generated by Django 3.1.4 on 2020-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_auto_20201230_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert_post',
            name='stars',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='stars',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='stars',
            field=models.IntegerField(default=1),
        ),
    ]
