# Generated by Django 3.1.4 on 2020-12-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_auto_20201230_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert_post',
            name='event',
        ),
        migrations.RemoveField(
            model_name='dinner_post',
            name='event',
        ),
        migrations.RemoveField(
            model_name='snack_post',
            name='event',
        ),
        migrations.AlterField(
            model_name='dinner_post',
            name='ingredient_1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
