# Generated by Django 3.1.4 on 2021-02-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0011_auto_20210201_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dessert_post',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='dinner_post',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='snack_post',
            name='prep_time',
        ),
    ]
