# Generated by Django 3.1.4 on 2021-02-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0018_auto_20210201_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert_post',
            old_name='cook_time',
            new_name='cook_time_lower',
        ),
        migrations.RenameField(
            model_name='dessert_post',
            old_name='prep_time',
            new_name='cook_time_upper',
        ),
        migrations.RenameField(
            model_name='dinner_post',
            old_name='cook_time',
            new_name='cook_time_lower',
        ),
        migrations.RenameField(
            model_name='dinner_post',
            old_name='prep_time',
            new_name='cook_time_upper',
        ),
        migrations.RenameField(
            model_name='snack_post',
            old_name='cook_time',
            new_name='cook_time_lower',
        ),
        migrations.RenameField(
            model_name='snack_post',
            old_name='prep_time',
            new_name='cook_time_upper',
        ),
        migrations.AddField(
            model_name='dessert_post',
            name='prep_time_lower',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dessert_post',
            name='prep_time_upper',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='prep_time_lower',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='prep_time_upper',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='prep_time_lower',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='prep_time_upper',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dessert_post',
            name='difficulty',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dessert_post',
            name='instructions',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dinner_post',
            name='ingredients',
            field=models.TextField(default='Placeholder', max_length=500),
        ),
        migrations.AlterField(
            model_name='dinner_post',
            name='instructions',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='snack_post',
            name='ingredients',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='snack_post',
            name='instructions',
            field=models.TextField(default='', max_length=500),
        ),
    ]
