# Generated by Django 3.1.4 on 2021-02-01 22:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0020_auto_20210201_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner_post',
            name='ingredients_1',
        ),
        migrations.RemoveField(
            model_name='dinner_post',
            name='ingredients_2',
        ),
        migrations.RemoveField(
            model_name='dinner_post',
            name='ingredients_3',
        ),
        migrations.RemoveField(
            model_name='dinner_post',
            name='ingredients_4',
        ),
    ]
