# Generated by Django 3.1.4 on 2021-02-01 22:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0021_auto_20210201_2225'),
    ]

    operations = [
    ]
