# Generated by Django 3.1.4 on 2021-02-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0022_auto_20210201_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_post',
            name='ingredients_1',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='ingredients_2',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='ingredients_3',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='ingredients_4',
            field=models.TextField(default='', max_length=500),
        ),
    ]
