# Generated by Django 3.1.4 on 2021-02-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0028_auto_20210203_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert_post',
            name='recipe_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='recipe_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='recipe_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
