# Generated by Django 3.1.4 on 2021-02-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0030_wine_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine_post',
            old_name='difficulty',
            new_name='region',
        ),
        migrations.AddField(
            model_name='wine_post',
            name='scents',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wine_post',
            name='tannins',
            field=models.CharField(default='', max_length=500),
        ),
    ]
