# Generated by Django 3.1.4 on 2021-02-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0032_auto_20210212_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine_post',
            name='article_id',
        ),
    ]
