# Generated by Django 3.1.4 on 2021-02-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0033_remove_wine_post_article_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert_post',
            old_name='difficulty',
            new_name='button_id',
        ),
        migrations.RenameField(
            model_name='dinner_post',
            old_name='difficulty',
            new_name='button_id',
        ),
        migrations.RenameField(
            model_name='snack_post',
            old_name='difficulty',
            new_name='button_id',
        ),
    ]
