# Generated by Django 3.1.4 on 2021-02-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0034_auto_20210215_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert_post',
            name='fryer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dessert_post',
            name='serving',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='fryer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='serving',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='fryer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='serving',
            field=models.CharField(default='', max_length=100),
        ),
    ]
