# Generated by Django 3.1.4 on 2021-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0035_auto_20210215_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert_post',
            name='stars',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='stars',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='stars',
            field=models.IntegerField(default=1),
        ),
    ]
