# Generated by Django 3.1.4 on 2021-02-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0036_auto_20210215_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert_post',
            name='stars',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='dinner_post',
            name='stars',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='snack_post',
            name='stars',
            field=models.IntegerField(default=''),
        ),
    ]
