# Generated by Django 3.1.4 on 2021-02-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0037_auto_20210215_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert_post',
            name='star_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dinner_post',
            name='star_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snack_post',
            name='star_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
