# Generated by Django 3.1.4 on 2021-02-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0038_auto_20210215_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.JPG', upload_to='image_posts')),
                ('description', models.TextField(default='.', max_length=500)),
            ],
        ),
    ]
