# Generated by Django 3.1.4 on 2021-03-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0039_tips_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine_Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('overview', models.TextField(default='.', max_length=100)),
                ('blend', models.TextField(default='.', max_length=20)),
            ],
        ),
    ]
