# Generated by Django 3.1.4 on 2021-03-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0040_wine_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine_post',
            name='article_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wine_post',
            name='article_type',
            field=models.CharField(default='', max_length=500),
        ),
    ]
