# Generated by Django 3.1.4 on 2021-03-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0041_auto_20210326_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine_post',
            name='article_type_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
