# Generated by Django 3.1.4 on 2021-03-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0042_wine_post_article_type_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine_post',
            name='article_type_url',
        ),
    ]
