# Generated by Django 3.1.4 on 2021-03-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0043_remove_wine_post_article_type_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_post',
            name='article_link',
            field=models.URLField(default=''),
        ),
    ]
