# Generated by Django 3.1.4 on 2021-03-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0044_auto_20210326_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_post',
            name='article_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
