# Generated by Django 3.1.4 on 2021-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0045_auto_20210326_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine_Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('overview', models.TextField(default='.', max_length=300)),
                ('tannin_lvl', models.IntegerField(default='.', max_length=20)),
                ('alcohol_lvl', models.IntegerField(default='.', max_length=20)),
                ('sweet_lvl', models.IntegerField(default='.', max_length=20)),
                ('body_lvl', models.IntegerField(default='.', max_length=20)),
                ('acid_lvl', models.IntegerField(default='.', max_length=20)),
                ('wine_id', models.CharField(default='.', max_length=30)),
                ('lat', models.IntegerField(default='.', max_length=10)),
                ('long', models.IntegerField(default='.', max_length=10)),
                ('aroma_1', models.IntegerField(default='.', max_length=20)),
                ('image_1', models.ImageField(default='default.JPG', upload_to='image_posts')),
                ('aroma_2', models.IntegerField(default='.', max_length=20)),
                ('image_2', models.ImageField(default='default.JPG', upload_to='image_posts')),
                ('aroma_3', models.IntegerField(default='.', max_length=20)),
                ('image_3', models.ImageField(default='default.JPG', upload_to='image_posts')),
                ('aroma_4', models.IntegerField(default='.', max_length=20)),
                ('image_4', models.ImageField(default='default.JPG', upload_to='image_posts')),
                ('aroma_5', models.IntegerField(default='.', max_length=20)),
                ('image_5', models.ImageField(default='default.JPG', upload_to='image_posts')),
            ],
        ),
    ]
