# Generated by Django 3.1.4 on 2021-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0046_wine_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_guide',
            name='acid_lvl',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='alcohol_lvl',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_1',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_2',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_3',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_4',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_5',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='body_lvl',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='lat',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='long',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='sweet_lvl',
            field=models.IntegerField(default='.'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='tannin_lvl',
            field=models.IntegerField(default='.'),
        ),
    ]
