# Generated by Django 3.1.4 on 2021-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0047_auto_20210328_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_guide',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
