# Generated by Django 3.1.4 on 2021-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0048_auto_20210328_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_1',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_2',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_3',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_4',
            field=models.CharField(default='.', max_length=30),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='aroma_5',
            field=models.CharField(default='.', max_length=30),
        ),
    ]
