# Generated by Django 3.1.4 on 2021-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0049_auto_20210328_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_guide',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
