# Generated by Django 3.1.4 on 2021-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0050_auto_20210328_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_guide',
            name='image_1',
            field=models.ImageField(default='default.JPG', upload_to='image_posts/icons_copy'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='image_2',
            field=models.ImageField(default='default.JPG', upload_to='image_posts/icons_copy'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='image_3',
            field=models.ImageField(default='default.JPG', upload_to='image_posts/icons_copy'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='image_4',
            field=models.ImageField(default='default.JPG', upload_to='image_posts/icons_copy'),
        ),
        migrations.AlterField(
            model_name='wine_guide',
            name='image_5',
            field=models.ImageField(default='default.JPG', upload_to='image_posts/icons_copy'),
        ),
    ]
