# Generated by Django 3.1.4 on 2021-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0052_auto_20210328_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_guide',
            name='long',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
