# Generated by Django 3.1.4 on 2021-03-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0053_auto_20210328_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine_guide',
            name='map_function',
            field=models.CharField(default='.', max_length=30),
        ),
    ]
