# Generated by Django 3.1.4 on 2021-04-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0054_wine_guide_map_function'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine_guide',
            old_name='map_function',
            new_name='wine_type',
        ),
        migrations.RemoveField(
            model_name='wine_guide',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='wine_guide',
            name='long',
        ),
    ]
