# Generated by Django 3.1.4 on 2021-04-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0055_auto_20210402_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine_guide',
            name='wine_location',
            field=models.CharField(default='.', max_length=30),
        ),
    ]
